Repository SITE-2022-W6/The-Foodie-Express-API, pull requests merged in 2022-07, with the labels that each got.

#23 Menu model refactor
  db.js
  foodie-express-schema.sql
  models/menu.js
  models/restaurant.js
  models/review.js
  routes/menu.js
Labels: refactor

#25 Add function to get restaurant given a city and state
  models/restaurant.js
  routes/restaurant.js
Labels: enhancement

#28 Major bug fixes and testing done for restaurant and menu models.
  foodie-express-schema.sql
  models/restaurant.js
  routes/restaurant.js
Labels: refactor

#31 Fix incorrect return when looking for a menu
  models/menu.js
  models/restaurant.js
  routes/restaurant.js
Labels: bug

#32 Getmenu
  models/menu.js
  models/restaurant.js
  routes/restaurant.js
Labels: enhancement

#33 Review model enhanced
  models/review.js
  routes/review.js
Labels: enhancement

#34 Change return info for menu
  foodie-express-schema.sql
  models/menu.js
  models/restaurant.js
Labels: refactor

#35 Implement function to get details on a specific menu item
  models/menu.js
  routes/menu.js
Labels: enhancement

#36 Modify function to get more restaurants from a location
  models/restaurant.js
  routes/restaurant.js
Labels: enhancement

#38 Small fix so api call can return more info for frontend
  models/restaurant.js
Labels: enhancement

#39 Get all reviews
  models/review.js
  routes/review.js
Labels: enhancement
