Repository SITE-2022-W6/The-Foodie-Express-API, pull requests merged in 2022-08, with the labels that each got.

#44 Saves status of restaurant location call
  models/restaurant.js
  routes/restaurant.js
Labels: enhancement

#43 Recommend algo
  app.js
  foodie-express-schema.sql
  models/review.js
  models/user.js
  routes/review.js
  routes/testRoutes.js
Labels: enhancement

#47 Implement function to get average rating for an item
  models/menu.js
  routes/menu.js
Labels: enhancement

#46 Create function to get all reviews for an item
  models/review.js
  routes/review.js
Labels: enhancement

#51 Fixed sql column type
  foodie-express-schema.sql
  routes/review.js
Labels: bug

#52 Get user by user id
  models/user.js
  routes/auth.js
Labels: enhancement

#53 Review refactor
  foodie-express-schema.sql
  models/preference.js
  models/review.js
Labels: refactor

#54 cleaned up routes url
  routes/review.js
Labels: refactor

#55 Update user
  models/user.js
  routes/auth.js
Labels: enhancement

#56 Change return of a function
  models/review.js
Labels: refactor

#58 Rec improved
  foodie-express-schema.sql
  models/preference.js
  models/restaurant.js
  models/review.js
  routes/restaurant.js
Labels: enhancement
